#!/usr/bin/env sh

# Description: Change directory using fzf
# 
# Dependencies: nnn-fzf-preview (script)
#               fd (optional)
#               bat (optional)
#               exa (optional)
# 
# Shell: POSIX compliant
# Author: Sergey Konkin


if test -x "$(command -v fd)"; then
    FD='fd --follow --relative-path --strip-cwd-prefix'
else
    FD='find -L | sed "s|^./||"'
fi
PREVIEW_WINDOW='hidden:wrap:down,70%'


found=$(
    FZF_DEFAULT_COMMAND="$FD" \
    fzf $FZF_DEFAULT_OPTS \
        --no-multi \
        --preview-window "$PREVIEW_WINDOW" \
        --preview 'nnn-fzf-preview {}' \
        --prompt 'fd-r> ' \
        --bind 'ctrl-p:toggle-preview' \
        --bind "ctrl-u:change-prompt(fd-u> )+reload($FD --unrestricted)" \
        --bind "ctrl-r:change-prompt(fd-r> )+reload($FD)" \
        --header 'C-p(review) C-u(nrestrictred) C-r(restricted)' 
)


if test -n "$found"; then
    if test -f "$found"; then
        sdir="$(dirname "$PWD/$found")"
    else
        sdir="$PWD/$found" 
    fi
    printf "%s" "0c$sdir" > "$NNN_PIPE"
fi

