#!/usr/bin/env sh

selection=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}

# clear screen
clear

# show git info
if [[ -f "$selection" ]]; then
    xargs -0 git diff < $selection
else
    git status -s $PWD
fi

# wait till quit
read

