#!/usr/bin/env sh

images="$(swayimg -m -w "${SWAYIMG_BG:-282c34}" "$PWD")"

if test -n "$images"; then
    selection=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}

    # write selection
    printf "%s" "$images" | tr '\n' '\0' > "$selection"

    # notify user
    tr '\0' '\n' <"$selection" | less -R
fi

