format="""
[┌──](bold dimmed white)\
$username\
$hostname\
$git_status\
$git_branch\
$directory\
$python\
$cmd_duration\
$line_break\
[└─> ](bold dimmed white)
"""
add_newline = true

[username]
format = ' [$user]($style)'
style_root = 'dimmed white'
style_user = 'dimmed white'
show_always = true

[hostname]
format = '[@$hostname$ssh_symbol]($style) '
style = 'dimmed white'
ssh_symbol = ' '
trim_at = '-'
disabled = false
ssh_only = false

[git_status]
format = '[$all_status ]($style)'
style = 'bold green'
ignore_submodules = true

[git_branch]
format = '[$branch:]($style)'
style = 'bold green'
symbol = ''

[directory]
format = '[$path]($style) '
style = 'bold blue'
truncate_to_repo = true
truncation_length = 1
truncation_symbol = ''

[python]
format = '[$symbol$virtualenv]($style)'
style = 'magenta'
symbol = ' '

[cmd_duration]
format = '[$duration]($style)'
style = 'yellow'
min_time = 10000  # ms
disabled = false
show_notifications = false


[sudo]
disabled = true

[battery]
disabled = true

[time]
disabled = true

[character]
disabled = true

[status]
disabled = true

[git_commit]
disabled = true

[git_metrics]
disabled = true

[aws]
symbol = ' '
disabled = true

[conda]
symbol = ' '
disabled = true

[dart]
symbol = ' '
disabled = true

[docker_context]
symbol = ' '
disabled = true

[elixir]
symbol = ' '
disabled = true

[elm]
symbol = ' '
disabled = true

[golang]
symbol = ' '
disabled = true

[hg_branch]
symbol = ' '
disabled = true

[java]
symbol = ' '
disabled = true

[julia]
symbol = ' '
disabled = true

[nim]
symbol = ' '
disabled = true

[nix_shell]
symbol = ' '
disabled = true

[nodejs]
symbol = ' '
disabled = true

[package]
symbol = ' '
disabled = true

[perl]
symbol = ' '
disabled = true

[php]
symbol = ' '
disabled = true

[ruby]
symbol = ' '
disabled = true

[rust]
symbol = ' '
disabled = true

[swift]
symbol = 'ﯣ '
disabled = true
